basePath: /
definitions:
  userControllerDto.CreateRequest:
    properties:
      id:
        type: string
      nickname:
        type: string
      password:
        type: string
    type: object
  userControllerDto.CreateResponse:
    properties:
      code:
        type: string
    type: object
host: localhost:9999
info:
  contact:
    email: den.shin.dev@gmail.com
    name: Den
  description: 당신의 정산을 쉽게 해줄 API
  title: Settlement support API
  version: "1.0"
paths:
  /users:
    post:
      consumes:
      - application/json
      description: Create an account
      parameters:
      - description: CreateUserRequest
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/userControllerDto.CreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: CreateUserResponse
          schema:
            $ref: '#/definitions/userControllerDto.CreateResponse'
      summary: Create an account
      tags:
      - User
swagger: "2.0"
