basePath: /
definitions:
  groupControllerCommandDto.CreateRequest:
    properties:
      title:
        type: string
    type: object
  groupControllerCommandDto.CreateResponse:
    description: SUCCESS 만이 성공
    properties:
      code:
        example: SUCCESS
        type: string
      group:
        $ref: '#/definitions/groupControllerCommandDto.Group'
    type: object
  groupControllerCommandDto.CreateResponseError:
    description: Create 의 오류응답
    properties:
      code:
        type: string
      errorMessage:
        type: string
    type: object
  groupControllerCommandDto.Group:
    properties:
      title:
        type: string
      uuid:
        type: string
    type: object
  userControllerCommandDto.CreateRequest:
    properties:
      id:
        type: string
      nickname:
        type: string
      password:
        type: string
    type: object
  userControllerCommandDto.CreateResponse:
    description: SUCCESS 만이 성공
    properties:
      code:
        example: SUCCESS
        type: string
    type: object
  userControllerCommandDto.CreateResponseError:
    description: Create 의 오류응답
    properties:
      code:
        type: string
      errorMessage:
        type: string
    type: object
host: localhost:9999
info:
  contact:
    email: den.shin.dev@gmail.com
    name: Den
  description: 당신의 정산을 쉽게 해줄 API
  title: Settlement support API
  version: "0.1"
paths:
  /groups:
    post:
      consumes:
      - application/json
      description: Create a group
      parameters:
      - description: CreateGroupRequest
        in: body
        name: group
        required: true
        schema:
          $ref: '#/definitions/groupControllerCommandDto.CreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: CreateGroupResponse
          schema:
            $ref: '#/definitions/groupControllerCommandDto.CreateResponse'
        "400":
          description: CreateGroupErrorResponse
          schema:
            $ref: '#/definitions/groupControllerCommandDto.CreateResponseError'
      summary: Create a group
      tags:
      - Group
  /users:
    post:
      consumes:
      - application/json
      description: Create an account
      parameters:
      - description: CreateUserRequest
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/userControllerCommandDto.CreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: CreateUserResponse
          schema:
            $ref: '#/definitions/userControllerCommandDto.CreateResponse'
        "400":
          description: CreateUserErrorResponse
          schema:
            $ref: '#/definitions/userControllerCommandDto.CreateResponseError'
      summary: Create an account
      tags:
      - User
swagger: "2.0"
